### ISSUE TITLE
target ninja-native is currently broken in main

### ISSUE THREAD

**Issue by h5b** [jhnc-oss/yocto-build#11]
Bitbake fails on any target which depends on ninja-native.

Running ```bitbake ninja-native [-c clean]``` results in the following error message:
```ERROR: ninja-native-1.10.0-r0 do_compile: Execution of '/opt/yocto/build/tmp/work/x86_64-linux/ninja-native/1.10.0-r0/temp/run.do_compile.91967' failed with exit code 1:
re2c: /opt/yocto/build/tmp/sysroots-uninative/x86_64-linux/usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by re2c)
bootstrapping ninja...
Traceback (most recent call last):
  File "/opt/yocto/build/tmp/work/x86_64-linux/ninja-native/1.10.0-r0/git/./configure.py", line 480, in <module>
    if has_re2c():
  File "/opt/yocto/build/tmp/work/x86_64-linux/ninja-native/1.10.0-r0/git/./configure.py", line 477, in has_re2c
    return int(proc.communicate()[0], 10) >= 1103
ValueError: invalid literal for int() with base 10: b''
WARNING: /opt/yocto/build/tmp/work/x86_64-linux/ninja-native/1.10.0-r0/temp/run.do_compile.91967:1 exit 1 from 'python3 ./configure.py --bootstrap'

ERROR: Logfile of failure stored in: /opt/yocto/build/tmp/work/x86_64-linux/ninja-native/1.10.0-r0/temp/log.do_compile.91967
Log data follows:
| DEBUG: Executing shell function do_compile
| re2c: /opt/yocto/build/tmp/sysroots-uninative/x86_64-linux/usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by re2c)
| bootstrapping ninja...
| Traceback (most recent call last):
|   File "/opt/yocto/build/tmp/work/x86_64-linux/ninja-native/1.10.0-r0/git/./configure.py", line 480, in <module>
|     if has_re2c():
|   File "/opt/yocto/build/tmp/work/x86_64-linux/ninja-native/1.10.0-r0/git/./configure.py", line 477, in has_re2c
|     return int(proc.communicate()[0], 10) >= 1103
| **ValueError: invalid literal for int() with base 10: b''**
| WARNING: /opt/yocto/build/tmp/work/x86_64-linux/ninja-native/1.10.0-r0/temp/run.do_compile.91967:1 exit 1 from 'python3 ./configure.py --bootstrap'
| ERROR: Execution of '/opt/yocto/build/tmp/work/x86_64-linux/ninja-native/1.10.0-r0/temp/run.do_compile.91967' failed with exit code 1:
| re2c: /opt/yocto/build/tmp/sysroots-uninative/x86_64-linux/usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by re2c)
| bootstrapping ninja...
| Traceback (most recent call last):
|   File "/opt/yocto/build/tmp/work/x86_64-linux/ninja-native/1.10.0-r0/git/./configure.py", line 480, in <module>
|     if has_re2c():
|   File "/opt/yocto/build/tmp/work/x86_64-linux/ninja-native/1.10.0-r0/git/./configure.py", line 477, in has_re2c
|     return int(proc.communicate()[0], 10) >= 1103
| ValueError: invalid literal for int() with base 10: b''
| WARNING: /opt/yocto/build/tmp/work/x86_64-linux/ninja-native/1.10.0-r0/temp/run.do_compile.91967:1 exit 1 from 'python3 ./configure.py --bootstrap'
| 
ERROR: Task (virtual:native:/opt/yocto/build/../poky/meta/recipes-devtools/ninja/ninja_1.10.0.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 80 tasks of which 73 didn't need to be rerun and 1 failed.```

**Comment by h5b** [comment]
- [ ] A/B Testing FC34 Host native versus podman container
- [ ] gcc 11.1.1 versus 10.x (FC33)
- [ ] FC34's glibc versus UNINATIVE_MAXGLIBCVERSION (distro/include/yocto-uninative.inc)

**Comment by h5b** [comment]
Poky's (dunfell 23.0.9) sysroot does not match host system (FC34)
```
$ readelf -a -r /opt/yocto/build/tmp/sysroots-uninative/x86_64-linux/usr/lib/libstdc++.so.6.0.28  | grep GLIBCXX_3.4.29
```

**Comment by h5b** [comment]
We should address the issue and main while switching out current LTS-Branches dunfell-23.0.9 and dunfell 23.0.10 to use supported OS Fedora Core 32.

**Comment by h5b** [comment]
uninative upgrade to 3.3 supporting glibc 2.34 available:

https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=d9878e12b8b78074be1019679ce078940a79c875

**Comment by h5b** [comment]
This now needs some testing with host OS FC34 including switching to uninative upgrade 3.3 supporting glibc 2.34.

**Comment by h5b** [comment]
Issue no longer reproducible
